# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_architect', '0004_auto_20160807_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
