# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_architect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pub_date',
        ),
    ]
